from django.conf.urls.defaults import *


urlpatterns = patterns('basic.music.views',
    url(r'^genre/(?P<slug>[-\w]+)/$',
        view='genre_detail',
        name='music_genre_detail',
    ),
    url (r'^genre/$',
        view='genre_list',
        name='music_genre_list',
    ),
    url(r'^label/(?P<slug>[-\w]+)/$',
        view='label_detail',
        name='music_label_detail',
    ),
    url (r'^label/$',
        view='label_list',
        name='music_label_list',
    ),
    url(r'^band/(?P<slug>[-\w]+)/$',
        view='band_detail',
        name='music_band_detail',
    ),
    url (r'^band/$',
        view='band_list',
        name='music_band_list',
    ),
    url(r'^album/(?P<slug>[-\w]+)/$',
        view='album_detail',
        name='music_album_detail',
    ),
    url (r'^album/$',
        view='album_list',
        name='music_album_list',
    ),
    url(r'^track/(?P<slug>[-\w]+)/$',
        view='track_detail',
        name='music_track_detail',
    ),
    url (r'^track/$',
        view='track_list',
        name='music_track_list',
    ),
    (r'^(?P<model>[-\w]+)/add$', 'model_form',),
)


urlpatterns += patterns('',
    url (r'^$',
        view='django.views.generic.simple.direct_to_template',
        kwargs={'template': 'music/index.html'},
        name='music_index',
    ),
)
